name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: touch "ion-backend-legacy.3.27.0-dev-master-6481-bcg6571.zip"
      - name: Install Octopus CLI
        uses: OctopusDeploy/install-octopus-cli-action@v4
        with:
          version: 
      
      - name: Push Package to Octopus Deploy
        # You may pin to the exact commit or the version.
        # uses: OctopusDeploy/push-package-action@035fb4fdbe77401574ec62275f9a531c570bd420
        uses: OctopusDeploy/push-package-action@v4
        with:
          # A multi-line list of packages to push to Octopus Deploy.
          packages: |
            ion-backend-legacy.3.27.0-dev-master-6481-bcg6571.zip
          # Determines the action to perform with package if it already exists in the repository. Valid values are "FailIfExists", "OverwriteExisting", and "IgnoreIfExists".
          overwrite_mode: OverwriteExisting
          # The API key used to access Octopus Deploy. You must provide an API key or username and password. If the guest account is enabled, a key of API-GUEST may be used. It is strongly recommended that this value retrieved from a GitHub secret.
          api_key: ${{secrets.OctopusAPIKey}}
          # The base URL hosting Octopus Deploy (i.e. "https://octopus.example.com/"). It is recommended to retrieve this value from an environment variable.
          server: ${{secrets.OctopusServer}}
          # The name or ID of a space within which this command will be executed. If omitted, the default space will be used.
          space: Dom
          
      
